// <auto-generated by FIX-20250909-phase2c>
using System;
using System.Reflection;

namespace Infrastructure
{
    public partial class PortfoliosRepository
    {
        /// <summary>
        /// Permissive ctor so tests that pass a SqliteDb (or similar) still compile.
        /// Tries to extract a ConnectionString/ConnString property; falls back to in-memory.
        /// </summary>
        public PortfoliosRepository(object dbOrConn)
        {
            if (dbOrConn is string s)
            {
                _connectionString = s;
                return;
            }

            var t = dbOrConn?.GetType();
            var prop = t?.GetProperty("ConnectionString", BindingFlags.Public | BindingFlags.Instance)
                    ?? t?.GetProperty("ConnString", BindingFlags.Public | BindingFlags.Instance);
            var val = prop?.GetValue(dbOrConn)?.ToString();

            _connectionString = string.IsNullOrWhiteSpace(val) ? "Data Source=:memory:" : val!;
        }
    }
}
