// <auto-generated by FIX-20250909-phase2c>
using System.Collections.Generic;

namespace Domain
{
    public record AllocationRow(string Ticker, decimal Weight);

    /// <summary>
    /// Canonical portfolio summary used across Presentation/Services/tests.
    /// </summary>
    public class PortfolioSummary
    {
        public int PortfolioId { get; init; }
        public string Name { get; init; } = string.Empty;

        // Always non-null
        public List<AllocationRow> Allocation { get; init; } = new();

        // Simple financial rollups (tests read these members)
        public decimal TotalMarketValue { get; init; }
        public decimal TotalCost { get; init; }
        public decimal GainLoss => TotalMarketValue - TotalCost;

        public PortfolioSummary() { }

        public PortfolioSummary(
            int portfolioId,
            string name,
            List<AllocationRow>? allocation = null,
            decimal totalMarketValue = 0,
            decimal totalCost = 0)
        {
            PortfolioId = portfolioId;
            Name = name;
            Allocation = allocation ?? new();
            TotalMarketValue = totalMarketValue;
            TotalCost = totalCost;
        }
    }
}
