// <auto-generated stub by FIX-20250909-phase2c>
namespace Services
{
    /// <summary>Minimal stub to satisfy DI & compile; replace with real logic later.</summary>
    public class BriefingService { }
}
